export const reportListAll = [
    {
        status: "SUCCESS",
        message: "Success!!",
        response: {
          processedStatusCount: {
            processedStatus: {
              DECLINED: 5,
              PENDING: 111,
              AUDIT_DECLINED: 0,
              ABORTED_BY_CRON: 6,
              ALLOCATED: 0,
              AUDITED: 0,
              HOLD: 13,
              AUDITHOLD: 0,
              AUDIT_PENDING: 0,
              NOTCOMPUTED: 9,
              COMPUTED: 151,
              REAUDIT: 0,
              COMPLETED: 206,
              NOT_AUDIT: 0
            },
            auditedStatus: {
              PENDING: 0,
              DECLINED: 0,
              AUDIT_DECLINED: 9,
              ABORTED_BY_CRON: 0,
              ALLOCATED: 0,
              AUDITED: 72,
              HOLD: 0,
              AUDITHOLD: 7,
              AUDIT_PENDING: 62,
              NOTCOMPUTED: 0,
              COMPUTED: 0,
              REAUDIT: 1,
              COMPLETED: 0,
              NOT_AUDIT: 243
            }
          },
          response: {
            pageNumber: 0,
            totalElements: 683,
            pageSize: 15,
            data: [
              {
                patientId: "EH-client-test-02",
                patientAllocated: "vignesh@encipherhealth.onmicrosoft.com",
                patientAllocatedFirstName: "Gabriel",
                patientAllocatedLastName: "Jenkins",
                patientAllocatedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/080e0d00-56fb-4b45-941e-c6787f47dad3.jpg",
                patientName: "xxxxxxxx",
                validDisease: null,
                validDiseaseCount: 7,
                invalidDisease: null,
                inValidDiseaseCount: 5,
                deletedDiseases: null,
                deletedDiseaseCount: null,
                unmatchedDisease: null,
                rafScore: null,
                flag: null,
                comment: null,
                unmatchedDiseaseCount: 2,
                machineAvgScore: null,
                l1AuditorAvgScore: null,
                dueDate: "2024-04-30T00:00:00Z",
                processedDate: null,
                processedStatus: "PENDING",
                auditedBy: null,
                auditedByFirstName: null,
                auditedByLastName: null,
                auditedByProfileImage: null,
                auditedStatus: "NOT_AUDIT",
                auditAllocatedBy: null,
                auditAllocatedByFirstName: null,
                auditAllocatedByLastName: null,
                auditAllocatedByProfileImage: null,
                auditDueDate: null,
                auditedDate: null,
                auditedAssigned: null,
                auditedAssignedFirstName: null,
                auditedAssignedLastName: null,
                auditedAssignedProfileImage: null,
                l2addedCount: null,
                rafSum: 0.641,
                declineNotes: null,
                auditDeclineNotes: null
              },
              {
                patientId: "EH-200123",
                patientAllocated: "peter@encipherhealth.onmicrosoft.com",
                patientAllocatedFirstName: "Peter",
                patientAllocatedLastName: "Thompson",
                patientAllocatedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/2884a6c4-02ce-4b9d-8e43-e8d9b14ee98e.jpeg",
                patientName: "sam",
                validDisease: null,
                validDiseaseCount: 3,
                invalidDisease: null,
                inValidDiseaseCount: 2,
                deletedDiseases: null,
                deletedDiseaseCount: null,
                unmatchedDisease: null,
                rafScore: null,
                flag: {
                  2023: [
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200123",
                      comments: "test",
                      flag: "MRN_ID_MISMATCH",
                      commentCreatedAt: "2024-04-27T06:32:53.623Z",
                      commentCreatedBy: "henry@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: null
                    },
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200123",
                      comments: "test",
                      flag: null,
                      commentCreatedAt: "2024-04-29T06:40:16.331Z",
                      commentCreatedBy: "peter@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: "dc44fa22-c406-489e-a1a9-f529c4a82579"
                    }
                  ]
                },
                comment: null,
                unmatchedDiseaseCount: 2,
                machineAvgScore: null,
                l1AuditorAvgScore: null,
                dueDate: "2024-04-26T00:00:00Z",
                processedDate: "2024-04-26T13:49:41.618Z",
                processedStatus: "COMPLETED",
                auditedBy: null,
                auditedByFirstName: null,
                auditedByLastName: null,
                auditedByProfileImage: null,
                auditedStatus: "NOT_AUDIT",
                auditAllocatedBy: null,
                auditAllocatedByFirstName: null,
                auditAllocatedByLastName: null,
                auditAllocatedByProfileImage: null,
                auditDueDate: null,
                auditedDate: null,
                auditedAssigned: null,
                auditedAssignedFirstName: null,
                auditedAssignedLastName: null,
                auditedAssignedProfileImage: null,
                l2addedCount: 1,
                rafSum: 0.327,
                declineNotes: null,
                auditDeclineNotes: null
              },
              {
                patientId: "EH-123002",
                patientAllocated: "peter@encipherhealth.onmicrosoft.com",
                patientAllocatedFirstName: "Peter",
                patientAllocatedLastName: "Thompson",
                patientAllocatedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/2884a6c4-02ce-4b9d-8e43-e8d9b14ee98e.jpeg",
                patientName: "Thomas",
                validDisease: null,
                validDiseaseCount: 3,
                invalidDisease: null,
                inValidDiseaseCount: 2,
                deletedDiseases: null,
                deletedDiseaseCount: null,
                unmatchedDisease: null,
                rafScore: null,
                flag: null,
                comment: null,
                unmatchedDiseaseCount: 0,
                machineAvgScore: null,
                l1AuditorAvgScore: null,
                dueDate: "2024-04-25T00:00:00Z",
                processedDate: "2024-04-29T11:18:49.654Z",
                processedStatus: "PENDING",
                auditedBy: null,
                auditedByFirstName: null,
                auditedByLastName: null,
                auditedByProfileImage: null,
                auditedStatus: "NOT_AUDIT",
                auditAllocatedBy: null,
                auditAllocatedByFirstName: null,
                auditAllocatedByLastName: null,
                auditAllocatedByProfileImage: null,
                auditDueDate: null,
                auditedDate: null,
                auditedAssigned: null,
                auditedAssignedFirstName: null,
                auditedAssignedLastName: null,
                auditedAssignedProfileImage: null,
                l2addedCount: null,
                rafSum: 0.327,
                declineNotes: null,
                auditDeclineNotes: null
              },
              {
                patientId: "EH-DEMO-001",
                patientAllocated: "peter@encipherhealth.onmicrosoft.com",
                patientAllocatedFirstName: "Peter",
                patientAllocatedLastName: "Thompson",
                patientAllocatedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/2884a6c4-02ce-4b9d-8e43-e8d9b14ee98e.jpeg",
                patientName: "R***** J****** C",
                validDisease: null,
                validDiseaseCount: 5,
                invalidDisease: null,
                inValidDiseaseCount: 6,
                deletedDiseases: null,
                deletedDiseaseCount: null,
                unmatchedDisease: null,
                rafScore: null,
                flag: null,
                comment: null,
                unmatchedDiseaseCount: 0,
                machineAvgScore: null,
                l1AuditorAvgScore: null,
                dueDate: "2024-04-24T11:05:42.029Z",
                processedDate: "2024-04-23T11:05:42.029Z",
                processedStatus: "COMPLETED",
                auditedBy: "Charlie@encipherhealth.onmicrosoft.com",
                auditedByFirstName: "Charlie",
                auditedByLastName: "Smith",
                auditedByProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/74279b3d-e240-48ef-af2d-fa8a976a0334.png",
                auditedStatus: "AUDIT_PENDING",
                auditAllocatedBy: "Andrew@encipherhealth.onmicrosoft.com",
                auditAllocatedByFirstName: "Andrew",
                auditAllocatedByLastName: "Martinez",
                auditAllocatedByProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/7947cb26-3fc7-4229-9a3c-73142435539d.png",
                auditDueDate: "2024-04-25T11:05:42.029Z",
                auditedDate: "2024-04-26T14:23:18.005Z",
                auditedAssigned: "Charlie@encipherhealth.onmicrosoft.com",
                auditedAssignedFirstName: "Charlie",
                auditedAssignedLastName: "Smith",
                auditedAssignedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/74279b3d-e240-48ef-af2d-fa8a976a0334.png",
                l2addedCount: null,
                rafSum: 0.201,
                declineNotes: {
                  2023: "  "
                },
                auditDeclineNotes: {
                  2023: " "
                }
              },
              {
                patientId: "EH-200100",
                patientAllocated: "peter@encipherhealth.onmicrosoft.com",
                patientAllocatedFirstName: "Peter",
                patientAllocatedLastName: "Thompson",
                patientAllocatedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/2884a6c4-02ce-4b9d-8e43-e8d9b14ee98e.jpeg",
                patientName: "Deniel",
                validDisease: null,
                validDiseaseCount: 2,
                invalidDisease: null,
                inValidDiseaseCount: 2,
                deletedDiseases: null,
                deletedDiseaseCount: null,
                unmatchedDisease: null,
                rafScore: null,
                flag: {
                  2023: [
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200100",
                      comments: "Test",
                      flag: "PATIENT_NAME_MISSED",
                      commentCreatedAt: "2024-04-23T12:16:52.563Z",
                      commentCreatedBy: "peter@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: null
                    },
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200100",
                      comments: "test",
                      flag: "MRN_ID_MISMATCH",
                      commentCreatedAt: "2024-04-23T14:21:54.002Z",
                      commentCreatedBy: "peter@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: null
                    },
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200100",
                      comments: "test",
                      flag: "PATIENT_NAME_MISSED",
                      commentCreatedAt: "2024-04-26T06:36:27.748Z",
                      commentCreatedBy: "henry@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: null
                    },
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200100",
                      comments: "test",
                      flag: "PATIENT_NAME_MISSED",
                      commentCreatedAt: "2024-04-26T07:00:02.480Z",
                      commentCreatedBy: "henry@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: null
                    },
                    {
                      orgId: "daa95f13-8b1d-4dc3-8d1c-c15d192c6cd5",
                      patientId: "EH-200100",
                      comments: "test",
                      flag: "PATIENT_NAME_MISSED",
                      commentCreatedAt: "2024-04-26T07:05:20.623Z",
                      commentCreatedBy: "henry@encipherhealth.onmicrosoft.com",
                      year: 2023,
                      flagDetailsId: null
                    }
                  ]
                },
                comment: null,
                unmatchedDiseaseCount: 1,
                machineAvgScore: null,
                l1AuditorAvgScore: null,
                dueDate: "2024-04-24T00:00:00Z",
                processedDate: "2024-04-23T12:19:11.647Z",
                processedStatus: "COMPLETED",
                auditedBy: "Charlie@encipherhealth.onmicrosoft.com",
                auditedByFirstName: "Charlie",
                auditedByLastName: "Smith",
                auditedByProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/74279b3d-e240-48ef-af2d-fa8a976a0334.png",
                auditedStatus: "AUDITED",
                auditAllocatedBy: "Andrew@encipherhealth.onmicrosoft.com",
                auditAllocatedByFirstName: "Andrew",
                auditAllocatedByLastName: "Martinez",
                auditAllocatedByProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/7947cb26-3fc7-4229-9a3c-73142435539d.png",
                auditDueDate: "2024-04-24T23:00:00.999Z",
                auditedDate: "2024-04-25T13:25:03.061Z",
                auditedAssigned: "Charlie@encipherhealth.onmicrosoft.com",
                auditedAssignedFirstName: "Charlie",
                auditedAssignedLastName: "Smith",
                auditedAssignedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/74279b3d-e240-48ef-af2d-fa8a976a0334.png",
                l2addedCount: null,
                rafSum: 0.327,
                declineNotes: {
                  2023: " "
                },
                auditDeclineNotes: {
                  2023: " "
                }
              },
              {
                patientId: "EH-DEMO-002",
                patientAllocated: "peter@encipherhealth.onmicrosoft.com",
                patientAllocatedFirstName: "Peter",
                patientAllocatedLastName: "Thompson",
                patientAllocatedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/2884a6c4-02ce-4b9d-8e43-e8d9b14ee98e.jpeg",
                patientName: "T****** G******",
                validDisease: null,
                validDiseaseCount: 6,
                invalidDisease: null,
                inValidDiseaseCount: 13,
                deletedDiseases: null,
                deletedDiseaseCount: null,
                unmatchedDisease: null,
                rafScore: null,
                flag: null,
                comment: null,
                unmatchedDiseaseCount: 2,
                machineAvgScore: null,
                l1AuditorAvgScore: null,
                dueDate: "2024-04-23T20:00:00Z",
                processedDate: "2024-04-23T05:12:37.598Z",
                processedStatus: "COMPLETED",
                auditedBy: null,
                auditedByFirstName: null,
                auditedByLastName: null,
                auditedByProfileImage: null,
                auditedStatus: "AUDIT_PENDING",
                auditAllocatedBy: "Andrew@encipherhealth.onmicrosoft.com",
                auditAllocatedByFirstName: "Andrew",
                auditAllocatedByLastName: "Martinez",
                auditAllocatedByProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/7947cb26-3fc7-4229-9a3c-73142435539d.png",
                auditDueDate: "2024-04-23T23:00:00.999Z",
                auditedDate: null,
                auditedAssigned: "Charlie@encipherhealth.onmicrosoft.com",
                auditedAssignedFirstName: "Charlie",
                auditedAssignedLastName: "Smith",
                auditedAssignedProfileImage: "https://cogentaifiles.blob.core.windows.net/profileimages/74279b3d-e240-48ef-af2d-fa8a976a0334.png",
                l2addedCount: null,
                rafSum: 0.434,
                declineNotes: null,
                auditDeclineNotes: null
              }
           
            ]
          },
          reviewerAllocationCount: [
          
            {
              username: "jansi01@encipherhealth.onmicrosoft.com",
              count: 23,
              userNameDTO: {
                firstName: "Jansi",
                lastName: "Patel",
                userName: "jansi01@encipherhealth.onmicrosoft.com",
                profileImageUrl: "https://cogentaifiles.blob.core.windows.net/profileimages/9c81a14f-7154-4ea9-9190-e52ad210e244.jpeg"
              }
            },
            {
              username: "johnathan@encipherhealth.onmicrosoft.com",
              count: 15,
              userNameDTO: {
                firstName: "Johnathan",
                lastName: "James",
                userName: "johnathan@encipherhealth.onmicrosoft.com",
                profileImageUrl: null
              }
            },
            {
              username: "ajith01@encipherhealth.onmicrosoft.com",
              count: 1,
              userNameDTO: {
                firstName: "Sebastian",
                lastName: "Miller",
                userName: "ajith01@encipherhealth.onmicrosoft.com",
                profileImageUrl: "https://cogentaifiles.blob.core.windows.net/profileimages/3e609e49-b7e6-47ee-9023-3fb0136e0fd7.jpeg"
              }
            }
          ]
        }
      }
    ]
